### PR TITLE
Add Internationalization to CoinOS

### PR DESCRIPTION
**Pull request by ahopk127**
Hi, I think my internationalization feature branch is developed enough that I can merge it into master!

# Features Implemented in this Branch
- Localization into any language by editing JSON and JS files
- Automatic language selection based on user's browser preferences
- Manual locale selection (overrides automatic selection)
- Full documentation including a manual for translators
# What I Haven't Done
- I haven't localized every string, just the top bar (as a demo).  I plan to do that in master, and I plan to actually translate them to French after the GUI is finalized.
# Important Notes
- After this branch is merged, please make all text visible to the user internationalizable by giving it an ID and replacing the text with `{$_('stringID')}`.  Put the actual text in `src/locales/en.json`.  I will do this for all of the existing strings, but please do this for any new strings you add.

### CODE REVIEW

**Review by secondl1ght — APPROVED** [review]
Nice work @ahopk127! 
I made some minor adjustments/fixes which I pushed directly to your branch if that's ok?

Here is a summary:
- fixed a couple typos in readme
- moved the locale selector from the app header to the settings page - I think it makes sense to have it there
- added a style prop to the `LocaleSelector` comp so you can style it on different pages
- I added categories to the locales JSON files, I think this will help keep that file more organized - so for example now we have a `nav` category with the translations in a lower level object that you can access with `nav.startInSeconds`.
- I also added some code to the `__layout` file that was recommended here: https://github.com/kaisermann/svelte-i18n/blob/HEAD/docs/Getting%20Started.md#4-initializing - it will wait for the locale data to load before rendering the app
- moved the locale selector to the left side of the landing nav next to the CoinOS logo (I think it looks better over here)
- small bug fixes

I only have one other comment and question for you:

1. it would be nice to update the screenshots in the README to use some real arrow icons and text instead of just MS paint style graphics (not a big deal though :P)

2. I didn't see anywhere where we are persisting the selectors language, it is only stored in a `store` right? so if the user refreshes the page they will lose their selected language. We should probably add this to either `localStorage` or a cookie?

**Comment by ahopk127** [comment]
Yeah, pushing to my branch is fine.  If I didn't want that, I would keep it local.

I've glanced through your changes and I think they're mostly good.  The only one that might concern me is the JSON categories, because those might make the localization process harder.  I specifically designed the process & instructions so that someone without technical experience can do it (and I just pushed some documentation changes that should hopefully address this).

About your concerns, I am merging right now because I want the system to be in master so I can start moving strings to IDs without creating problems.  This isn't done - I haven't even added much of a French translation either!  I'll make sure to update the screenshots and persist the language after this is merged in.

**Comment by secondl1ght** [comment]
Awesome sounds good! This will be really cool to have CoinOS in many languages and easy for contributors to translate.

**Comment by ahopk127** [comment]
Just added locale persistence with `localStorage`.  I think that's worth including in the merge.

**Pull request merged**
